graph LR
A(Hexo 构建) --> B(基础环境)
    B --> B1(安装Git)
    B --> B2(安装Node.js)
A --> C(安装Hexo框架)
    C --> C1(npm install -g hexo-cli)
    C --> C2(npm install blog)
    C --> C3(cd blog)
    C --> C4(npm install)
    C --> C5(hexo server)
A --> D(安装Hexo主题)
    D --> D1(npm i hexo theme-butterfly 或者 clone其他主题解压放置在 theme目录)
A --> E(部署到Github Pages)
    E --> E1(注册github)
    E --> E2(创建和用户名同名仓库)
    E --> E3(安装配置Hexo Git部署插件)
    E --> E4(推送Hexo博客到仓库)
    E --> E5(Github Pages设置)
A --> F(自定义域名解析)
    F --> F1(域名购买)
    F --> F2(域名解析到Github Pages)